apiVersion: v1
kind: Service
metadata:
  name: employee-rest-service
spec:
  selector:
    app: employees
  ports:
    - name: default
      protocol: TCP
      port: 9090
      targetPort: http
    - name: metrics
      protocol: TCP
      port: 9010
      targetPort: metrics
  type: LoadBalancer