DROP TABLE TBL_EMPLOYEE;
CREATE TABLE TBL_EMPLOYEE (
    ID NUMERIC(18) NOT NULL,
    CURRENCY VARCHAR(255),
    DEPARTMENT VARCHAR(255),
    EMAIL VARCHAR(255),
    EMPLOYMENT_DATE TIMESTAMP without time zone,
    FULL_NAME VARCHAR(255),
    MANAGER_EMAIL VARCHAR(255),
    PRICE VARCHAR(1024),
    CONSTRAINT TBL_EMPLOYEE_PKEY PRIMARY KEY (id)
)

